import { env } from "./env";
import type { AuditScope, AuditConfig, AuditReport, AuditFinding } from "@/types";
import { randomBytes } from "crypto";

export async function verifyPayment(
  paymentSignature: string,
  quote: { price: string; token: string; network: string; recipient: string; nonce: string; resourcePath: string }
): Promise<{ success: boolean; facilitatorResponse?: string; txHash?: string; error?: string }> {
  try {
    const response = await fetch(`${env.FACILITATOR_URL}/verify`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        paymentSignature,
        price: quote.price,
        token: quote.token,
        network: quote.network,
        recipient: quote.recipient,
        nonce: quote.nonce,
        resourcePath: quote.resourcePath,
      }),
    });
    const data = await response.json();
    if (response.ok && data.success) {
      return { success: true, facilitatorResponse: JSON.stringify(data) };
    }
    return { success: false, error: data.error || "VERIFICATION_FAILED" };
  } catch (err) {
    return { success: false, error: `FACILITATOR_ERROR: ${err}` };
  }
}

export async function settlePayment(
  paymentSignature: string,
  resourcePath: string
): Promise<{ success: boolean; txHash?: string; receipt?: string; error?: string }> {
  try {
    const response = await fetch(`${env.FACILITATOR_URL}/settle`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ paymentSignature, resourcePath }),
    });
    const data = await response.json();
    if (response.ok && data.success) {
      return { success: true, txHash: data.txHash, receipt: JSON.stringify(data) };
    }
    return { success: false, error: data.error || "SETTLEMENT_FAILED" };
  } catch (err) {
    return { success: false, error: `FACILITATOR_ERROR: ${err}` };
  }
}

export async function runAuditWorkflow(
  scope: AuditScope,
  config: AuditConfig
): Promise<AuditReport> {
  const findings: AuditFinding[] = [];

  for (const check of config.checks.filter((c) => c.enabled)) {
    const finding: AuditFinding = {
      id: `finding_${randomBytes(8).toString("hex")}`,
      checkId: check.id,
      checkName: check.name,
      severity: check.severity,
      title: `${check.name} — ${scope.target}`,
      description: `Automated check: ${check.description}. Target: ${scope.target} (${scope.type}). This is a placeholder finding generated by the audit engine. Define your own checks, severity rubric, and methodology.`,
      recommendation: `Review ${check.name.toLowerCase()} for ${scope.type} "${scope.target}" according to your organization's security policy.`,
      affectedContracts: scope.contractAddresses,
    };
    findings.push(finding);
  }

  const summary = {
    critical: findings.filter((f) => f.severity === "critical").length,
    high: findings.filter((f) => f.severity === "high").length,
    medium: findings.filter((f) => f.severity === "medium").length,
    low: findings.filter((f) => f.severity === "low").length,
    informational: findings.filter((f) => f.severity === "informational").length,
    total: findings.length,
  };

  const totalSeverity =
    summary.critical * 4 + summary.high * 3 + summary.medium * 2 + summary.low * 1;
  const passed = config.passFailPolicy === "advisory" || totalSeverity === 0;

  return {
    jobId: "",
    scope,
    findings,
    summary,
    passed,
    humanReviewed: false,
    generatedAt: new Date().toISOString(),
    methodology: config.customInstructions || "User-defined audit methodology. Configure checks, severity rubric, and pass/fail policy in your audit configuration.",
  };
}
